### ISSUE TITLE
请于此处报名翻译活动

### ISSUE THREAD

**Issue by TianFengshou** [apachecn/statsmodels-doc-zh#1]
目前首先翻译‘docs/zh/source’下的内容，如果想要参与该活动，请在此处报名。报名后fork文档参与活动即可。

我本人先认领三分文档，请按照一下格式报名。

翻译文档：

1. about.rst
1. multivariate.rst
1. anova.rst

翻译人：[Font Tian](https://github.com/FontTian)

校对活动将在之后发起。

**Comment by JiaHongshun** [comment]
翻译文档：
regression.rst

翻译人： @[JiaHongshun](https://github.com/JiaHongshun)

**Comment by lbllol365** [comment]
翻译文档：
1.install.rst
2.importpaths.rst

 翻译人 : [lbllol365](https://github.com/lbllol365)

**Comment by AllenZYJ** [comment]
翻译文档：
readme.md
翻译人@AllenZYJ

**Comment by keyianpai** [comment]
翻译文档：
glm.rst
翻译人@ keyianpai

**Comment by TianFengshou** [comment]
准备全部以md格式翻译,需要进行重新报名
